name: llmhe
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=6_kmp_llvm
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.9.1=hac33072_0
  - attr=2.5.2=h39aace5_0
  - blas=1.0=mkl
  - brotli-python=1.2.0=py310hba01987_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py310h34a4b09_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cpuonly=2.0=0
  - cpython=3.10.19=py310hd8ed1ab_2
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.1.0=0
  - cudatoolkit=11.8.0=h4ba93d1_13
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - faiss=1.9.0=py310cuda118hce52afa_0_cuda
  - faiss-gpu=1.9.0=h418687c_0
  - ffmpeg=8.0.0=gpl_hbbdf940_906
  - filelock=3.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gdk-pixbuf=2.44.4=h2b0a6b4_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - glslang=16.0.0=hfd11570_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310h63ebcad_2
  - graphite2=1.3.14=hecca717_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.1.0=h15599e2_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - intel-gmmlib=22.8.2=hb700be7_0
  - intel-media-driver=25.3.4=hecca717_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.26.0=hb700be7_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libass=0.17.4=h96ad9f0_0
  - libblas=3.9.0=20_linux64_mkl
  - libcap=2.77=h3ff7636_0
  - libcblas=3.9.0=20_linux64_mkl
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.1=hecca717_0
  - libfaiss=1.9.0=cuda118hf323835_0_cuda
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.0=h1fed272_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_5
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.9.0=20_linux64_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libopenvino=2025.2.0=hb617929_1
  - libopenvino-auto-batch-plugin=2025.2.0=hed573e4_1
  - libopenvino-auto-plugin=2025.2.0=hed573e4_1
  - libopenvino-hetero-plugin=2025.2.0=hd41364c_1
  - libopenvino-intel-cpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-gpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-npu-plugin=2025.2.0=hb617929_1
  - libopenvino-ir-frontend=2025.2.0=hd41364c_1
  - libopenvino-onnx-frontend=2025.2.0=h1862bb8_1
  - libopenvino-paddle-frontend=2025.2.0=h1862bb8_1
  - libopenvino-pytorch-frontend=2025.2.0=hecca717_1
  - libopenvino-tensorflow-frontend=2025.2.0=h0767aad_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hecca717_1
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.51=h421ea60_0
  - libprotobuf=6.31.1=h49aed37_2
  - librsvg=2.60.0=h61e6d4b_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=15.1.0=h4852527_5
  - libsystemd0=258.2=h6569c3e_1
  - libtiff=4.7.1=h9d88235_1
  - libudev1=258.2=h6569c3e_1
  - libunwind=1.8.3=h65a8314_0
  - liburing=2.12=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.41.2=he9a06e4_0
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h54a6638_2
  - libvpl=2.15.0=h54a6638_1
  - libvpx=1.14.1=hac33072_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.0=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=3.0.3=py310h3406613_0
  - mkl=2023.2.0=ha770c72_50498
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.4.2=pyh267e887_2
  - numpy=1.26.4=py310hb13e2d6_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h0158d43_1
  - pango=1.56.4=hadf4263_0
  - pcre2=10.46=h1321c63_0
  - pillow=12.0.0=py310h049bd52_1
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=h9a8bead_2
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=h3c07f61_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytorch=2.3.0=py3.10_cpu_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cpu
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310h3406613_0
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhd8ed1ab_0
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.2.26=h68140b3_0
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.4=h3e344bc_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - spirv-tools=2025.4=hb700be7_0
  - svt-av1=3.1.2=hecca717_0
  - sympy=1.14.0=pyh2585a3b_105
  - sysroot_linux-64=2.34=h087de78_2
  - tbb=2021.13.0=h8d10470_4
  - tk=8.6.13=noxft_hd72426e_102
  - torchaudio=2.3.0=py310_cpu
  - torchvision=0.18.0=py310_cpu
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wayland=1.24.0=h3e06ad9_0
  - wayland-protocols=1.46=hd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - yaml=0.2.5=h280c20c_3
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstandard=0.25.0=py310h139afa4_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - alembic==1.17.2
      - annotated-doc==0.0.4
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - black==25.11.0
      - blinker==1.9.0
      - blis==1.3.3
      - cachetools==6.2.2
      - catalogue==2.0.10
      - cbor==1.0.0
      - cfgv==3.5.0
      - click==8.3.1
      - clin-gnn-rac==0.1.0
      - cloudpathlib==0.23.0
      - coloredlogs==15.0.1
      - colorlog==6.10.1
      - confection==0.1.5
      - cryptography==46.0.3
      - cycler==0.12.1
      - cymem==2.0.13
      - cython==3.2.1
      - databricks-sdk==0.73.0
      - distlib==0.4.0
      - distro==1.9.0
      - docker==7.1.0
      - faiss-cpu==1.13.0
      - fastapi==0.122.0
      - flagembedding==1.3.5
      - flask==3.1.2
      - flask-cors==6.0.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.43.0
      - graphene==3.4.3
      - graphql-core==3.2.7
      - graphql-relay==3.2.0
      - greenlet==3.2.4
      - gunicorn==23.0.0
      - huey==2.5.4
      - humanfriendly==10.0
      - identify==2.6.15
      - ijson==3.4.0.post0
      - importlib-metadata==8.7.0
      - iniconfig==2.3.0
      - inscriptis==2.7.0
      - ir-datasets==0.5.11
      - isort==7.0.0
      - itsdangerous==2.2.0
      - jiter==0.12.0
      - kiwisolver==1.4.9
      - lightgbm==4.6.0
      - lz4==4.4.5
      - mako==1.3.10
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - mlflow==3.6.0
      - mlflow-skinny==3.6.0
      - mlflow-tracing==3.6.0
      - murmurhash==1.0.15
      - mypy==1.18.2
      - mypy-extensions==1.1.0
      - nltk==3.9.2
      - nmslib==2.1.2
      - nodeenv==1.9.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvtx-cu12==12.1.105
      - onnxruntime==1.23.2
      - openai==2.8.1
      - opentelemetry-api==1.38.0
      - opentelemetry-proto==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - optuna==4.6.0
      - pathspec==0.12.1
      - platformdirs==4.5.0
      - pluggy==1.6.0
      - pre-commit==4.5.0
      - preshed==3.0.12
      - protobuf==6.33.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybind11==3.0.1
      - pygments==2.19.2
      - pyjnius==1.7.0
      - pyparsing==3.2.5
      - pyserini==0.40.0
      - pytest==9.0.1
      - pytokens==0.3.0
      - rich==14.2.0
      - rsa==4.9.1
      - ruff==0.14.6
      - sentencepiece==0.2.1
      - shellingham==1.5.4
      - smart-open==7.5.0
      - smmap==5.0.2
      - soupsieve==2.8
      - spacy==3.8.11
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlparse==0.5.3
      - srsly==2.5.2
      - starlette==0.50.0
      - thinc==8.3.10
      - tiktoken==0.12.0
      - tokenizers==0.21.4
      - tomli==2.3.0
      - torch==2.3.1
      - torch-geometric==2.7.0
      - torch-scatter==2.1.2+pt23cpu
      - torch-sparse==0.6.18+pt23cpu
      - transformers==4.51.3
      - trec-car-tools==2.6
      - triton==2.3.1
      - typer==0.20.0
      - typer-slim==0.20.0
      - unlzw3==0.2.3
      - uvicorn==0.38.0
      - virtualenv==20.35.4
      - warc3-wet==0.2.5
      - warc3-wet-clueweb09==0.2.5
      - wasabi==1.1.3
      - weasel==0.4.3
      - werkzeug==3.1.3
      - wrapt==2.0.1
      - zipp==3.23.0
      - zlib-state==0.1.10
prefix: /home/user/miniforge3/envs/llmhe
